document.write(typeof(5), "<br>");
const value1 = "5";
const value2 = 9;
let sum = value1 + value2;

console.log(sum);
document.write(sum, "<br>");
document.write(2E310, "<br>");
document.write(-3E310, "<br>");
document.write(1 > 2, "<br>");
document.write(1 < 2, "<br>");
document.write(1 == 1, "<br>");
document.write(1 == 2, "<br>");
X = 10;
Y = 10;
document.write(X === Y, "<br>");
X = 10;
Y = "Ten";
document.write(X === Y, "<br>");
X = 10;
Y = "10";
document.write(X === Y, "<br>");
X = 10;
Y = 11;
document.write(X === Y, "<br>");
document.write(1 == 1 && 2 == 2, "<br>");
document.write(1 == 1 && 2 == 3, "<br>");
document.write(1 == 1 || 2 == 3, "<br>");
document.write(1 == 2 || 2 == 3, "<br>");
document.write(2 != 1, "<br>");
document.write(1 != 1, "<br>");